version: '3.4'

services:
  phan2bai04:
    image: phan2bai04
    build:
      context: Phan2_Bai04
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
