version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword 
      MYSQL_USER: user                 
      MYSQL_PASSWORD: password          
      MYSQL_DATABASE: mydb              
    ports:
      - "3333:3306"                       
    volumes:
      - mysql_data:/var/lib/mysql         

volumes:
  mysql_data:
