version: '3.8'

services:
  react-app:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./build:/usr/share/nginx/html
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
